version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
