version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8000:8000"
    volumes:
      - .:/test
    working_dir: /test
    command: >
      sh -c "cd src &&
             pytest -c tests/pytest.ini --flake8"
