version: 2.1

orbs:
  codecov: codecov/codecov@1.1.3

jobs:
  build_and_test:
    working_directory: ~/ordersvc
    docker:
      - image: $DOCKER_IMAGE_TAG
    steps:
      - checkout
      - run:
          name: Install curl and bash
          command: |
            apk update
            apk add curl curl-dev
            apk add bash bash-dev
      - restore_cache:
          key: dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Package Setup
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest . --cov=. --cov-report=xml:./coverage.xml -c tests/pytest.ini --flake8
      - codecov/upload:
          file: 'coverage.xml'
          token: $CODECOV_TOKEN
      - persist_to_workspace:
          root: .
          paths:
              - .
  publish:
    docker:
      - image: docker:18.09.0
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_ID" --password-stdin
            docker build -f Dockerfile.prod -t $DOCKER_IMAGE_TAG .
            docker push $DOCKER_IMAGE_TAG
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: deploy
          command: |
            ssh ubuntu@ec2-3-34-190-105.ap-northeast-2.compute.amazonaws.com ./deploy.sh

workflows:
  version: 2
  test:
    jobs:
      - build_and_test
      - publish:
          requires:
            - build_and_test
      - deploy:
          requires:
            - publish
