version: '3'

services:
  blue:
    image: armada55/ordersvc:latest
    container_name: ordersvc-blue
    expose:
      - "8081"
    volumes:
      - ..:/app
    working_dir: /app
    networks:
      - backend
    entrypoint: >
      sh -c "cd src &&
             uvicorn main:app --workers 1 --host 0.0.0.0 --port 8081"

  green:
    image: armada55/ordersvc:latest
    container_name: ordersvc-green
    expose:
      - "8082"
    volumes:
      - ..:/app
    working_dir: /app
    networks:
      - backend
    entrypoint: >
      sh -c "cd src &&
             uvicorn main:app --workers 1 --host 0.0.0.0 --port 8082"
    
  proxy:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

networks:
  backend:
